// <auto-generated />
using System;
using Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datalayer.Migrations
{
    [DbContext(typeof(EshopContext))]
    [Migration("20200507112202_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Datalayer.Entities.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Kodeord")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("KundeId");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            KundeId = 1,
                            Adresse = "HAHA",
                            Efternavn = "Schultz",
                            Email = "niel862b@elevcampus.dk",
                            Fornavn = "Niels",
                            Kodeord = "Qwerty123"
                        },
                        new
                        {
                            KundeId = 2,
                            Adresse = "FakeHAHA",
                            Efternavn = "FakeSchultz",
                            Email = "Fakeniel862b@elevcampus.dk",
                            Fornavn = "FakeNiels",
                            Kodeord = "Qwerty123"
                        });
                });

            modelBuilder.Entity("Datalayer.Entities.Ordre", b =>
                {
                    b.Property<int>("OrdreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("KoebsDato")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.HasKey("OrdreId");

                    b.HasIndex("KundeId");

                    b.ToTable("Ordre");
                });

            modelBuilder.Entity("Datalayer.Entities.OrdreProdukt", b =>
                {
                    b.Property<int>("OrdreId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.Property<int>("Styk")
                        .HasColumnType("int");

                    b.HasKey("OrdreId", "ProduktId");

                    b.HasIndex("ProduktId");

                    b.ToTable("OrdreProdukt");
                });

            modelBuilder.Entity("Datalayer.Entities.Producent", b =>
                {
                    b.Property<int>("ProducentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProducentId");

                    b.ToTable("Producenter");

                    b.HasData(
                        new
                        {
                            ProducentId = 1,
                            Navn = "ASUS"
                        },
                        new
                        {
                            ProducentId = 2,
                            Navn = "Acer"
                        },
                        new
                        {
                            ProducentId = 3,
                            Navn = "Apple"
                        },
                        new
                        {
                            ProducentId = 4,
                            Navn = "Lenovo"
                        },
                        new
                        {
                            ProducentId = 5,
                            Navn = "DELL"
                        },
                        new
                        {
                            ProducentId = 6,
                            Navn = "HP"
                        },
                        new
                        {
                            ProducentId = 7,
                            Navn = "MSI"
                        },
                        new
                        {
                            ProducentId = 8,
                            Navn = "Samsung"
                        },
                        new
                        {
                            ProducentId = 9,
                            Navn = "LG"
                        },
                        new
                        {
                            ProducentId = 10,
                            Navn = "Razer"
                        },
                        new
                        {
                            ProducentId = 11,
                            Navn = "Steelseries"
                        });
                });

            modelBuilder.Entity("Datalayer.Entities.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("ProducentId")
                        .HasColumnType("int");

                    b.HasKey("ProduktId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("ProducentId");

                    b.ToTable("Produkter");

                    b.HasData(
                        new
                        {
                            ProduktId = 1,
                            KategoriId = 1,
                            Navn = "ASUS GeForce RTX 2080 SUPER ROG Strix Advanced",
                            Pris = 7319m,
                            ProducentId = 1
                        },
                        new
                        {
                            ProduktId = 2,
                            KategoriId = 1,
                            Navn = "MSI GeForce RTX 2080 SUPER SEA HAWK EK X",
                            Pris = 6999m,
                            ProducentId = 7
                        },
                        new
                        {
                            ProduktId = 3,
                            KategoriId = 1,
                            Navn = "ASUS Radeon RX 5500 XT ROG Strix OC 8GB",
                            Pris = 1999m,
                            ProducentId = 1
                        },
                        new
                        {
                            ProduktId = 4,
                            KategoriId = 1,
                            Navn = "ASUS GeForce GTX 1660 SUPER ROG Strix OC",
                            Pris = 2229m,
                            ProducentId = 1
                        },
                        new
                        {
                            ProduktId = 5,
                            KategoriId = 2,
                            Navn = "MSI GE75 Raider 17,3 FHD 240 Hz",
                            Pris = 19990m,
                            ProducentId = 7
                        },
                        new
                        {
                            ProduktId = 6,
                            KategoriId = 2,
                            Navn = "Acer Nitro 5 15,6 FHD 120 Hz",
                            Pris = 5290m,
                            ProducentId = 2
                        },
                        new
                        {
                            ProduktId = 7,
                            KategoriId = 2,
                            Navn = "MSI Prestige 15 15,6 Full HD",
                            Pris = 11995m,
                            ProducentId = 7
                        },
                        new
                        {
                            ProduktId = 8,
                            KategoriId = 2,
                            Navn = "ASUS ZenBook Pro Duo 15,6 UHD / 4K OLED Touch",
                            Pris = 21490m,
                            ProducentId = 1
                        },
                        new
                        {
                            ProduktId = 9,
                            KategoriId = 2,
                            Navn = "Acer Chromebook R13 CB5-312T 13.3 FHD",
                            Pris = 2495m,
                            ProducentId = 2
                        },
                        new
                        {
                            ProduktId = 10,
                            KategoriId = 2,
                            Navn = "Apple MacBook Pro laptop 16 1TB MVV med touch bar",
                            Pris = 21999m,
                            ProducentId = 3
                        },
                        new
                        {
                            ProduktId = 11,
                            KategoriId = 2,
                            Navn = "Lenovo ThinkPad P53 15,6 Workstation Pro Full HD",
                            Pris = 27990m,
                            ProducentId = 4
                        },
                        new
                        {
                            ProduktId = 12,
                            KategoriId = 2,
                            Navn = "Dell Vostro 3590 15,6 Full HD",
                            Pris = 5290m,
                            ProducentId = 5
                        },
                        new
                        {
                            ProduktId = 13,
                            KategoriId = 2,
                            Navn = "Dell XPS 13 7390 13,3 UHD / 4K Touch",
                            Pris = 13690m,
                            ProducentId = 5
                        },
                        new
                        {
                            ProduktId = 14,
                            KategoriId = 2,
                            Navn = "HP Spectre x360 15-df1012no 15,6 UHD OLED touch",
                            Pris = 17495m,
                            ProducentId = 6
                        },
                        new
                        {
                            ProduktId = 15,
                            KategoriId = 2,
                            Navn = "Razer Blade Pro 17,3 UHD / 4K touch 120 Hz",
                            Pris = 33495m,
                            ProducentId = 10
                        },
                        new
                        {
                            ProduktId = 16,
                            KategoriId = 3,
                            Navn = "Samsung Galaxy S20 Ultra 5G 128GB Grå",
                            Pris = 10499m,
                            ProducentId = 8
                        },
                        new
                        {
                            ProduktId = 17,
                            KategoriId = 3,
                            Navn = "Samsung Galaxy A51 128GB Sort",
                            Pris = 2789m,
                            ProducentId = 8
                        },
                        new
                        {
                            ProduktId = 18,
                            KategoriId = 3,
                            Navn = "iPhone 11 Pro Max 64 GB Grå",
                            Pris = 9649m,
                            ProducentId = 3
                        },
                        new
                        {
                            ProduktId = 19,
                            KategoriId = 3,
                            Navn = "Apple iPhone SE 64GB Sort",
                            Pris = 3699m,
                            ProducentId = 3
                        },
                        new
                        {
                            ProduktId = 20,
                            KategoriId = 4,
                            Navn = "Samsung 75 QLED Smart TV QE75Q60R",
                            Pris = 16990m,
                            ProducentId = 8
                        },
                        new
                        {
                            ProduktId = 21,
                            KategoriId = 4,
                            Navn = "Samsung 75 QLED Smart TV QE75Q90R",
                            Pris = 39990m,
                            ProducentId = 8
                        },
                        new
                        {
                            ProduktId = 22,
                            KategoriId = 4,
                            Navn = "LG 55 UHD OLED Smart TV OLED55C9",
                            Pris = 9990m,
                            ProducentId = 9
                        },
                        new
                        {
                            ProduktId = 23,
                            KategoriId = 4,
                            Navn = "LG 48 OLED TV OLED48CX6",
                            Pris = 11999m,
                            ProducentId = 9
                        },
                        new
                        {
                            ProduktId = 24,
                            KategoriId = 5,
                            Navn = "Razer BlackWidow Elite Gaming Tastatur",
                            Pris = 1399m,
                            ProducentId = 10
                        },
                        new
                        {
                            ProduktId = 25,
                            KategoriId = 5,
                            Navn = "ASUS ROG Strix Scope Gaming Tastatur",
                            Pris = 1099m,
                            ProducentId = 1
                        },
                        new
                        {
                            ProduktId = 26,
                            KategoriId = 5,
                            Navn = "SteelSeries Apex Pro Gaming Tastatur",
                            Pris = 1599m,
                            ProducentId = 11
                        },
                        new
                        {
                            ProduktId = 27,
                            KategoriId = 6,
                            Navn = "Razer Basilisk Ultimate Trådløs Gaming Mus",
                            Pris = 1349m,
                            ProducentId = 10
                        },
                        new
                        {
                            ProduktId = 28,
                            KategoriId = 6,
                            Navn = "ASUS ROG Chakram Trådløs Gaming Mus",
                            Pris = 1079m,
                            ProducentId = 1
                        },
                        new
                        {
                            ProduktId = 29,
                            KategoriId = 6,
                            Navn = "Steelseries Rival 710 Gaming Mus",
                            Pris = 799m,
                            ProducentId = 11
                        });
                });

            modelBuilder.Entity("Datalayer.Entities.ProduktBillede", b =>
                {
                    b.Property<int>("ProduktBilledeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Billede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.HasKey("ProduktBilledeId");

                    b.HasIndex("ProduktId");

                    b.ToTable("ProduktBillede");

                    b.HasData(
                        new
                        {
                            ProduktBilledeId = 1,
                            Billede = "https://www.elgiganten.dk/image/dv_web_D180001002410624/153758/lg-48-cx-4k-oled-tv-oled48cx.jpg?$fullsize$",
                            ProduktId = 23
                        },
                        new
                        {
                            ProduktBilledeId = 2,
                            Billede = "https://www.elgiganten.dk/image/dv_web_D180001002410670/153758/lg-48-cx-4k-oled-tv-oled48cx.jpg?$fullsize$",
                            ProduktId = 23
                        },
                        new
                        {
                            ProduktBilledeId = 3,
                            Billede = "https://www.elgiganten.dk/image/dv_web_D180001002410669/153758/lg-48-cx-4k-oled-tv-oled48cx.jpg?$prod_all4one$",
                            ProduktId = 23
                        },
                        new
                        {
                            ProduktBilledeId = 4,
                            Billede = "https://www.komplett.dk/img/p/1200/1135677.jpg",
                            ProduktId = 1
                        },
                        new
                        {
                            ProduktBilledeId = 5,
                            Billede = "https://www.komplett.dk/img/p/1200/1139034.jpg",
                            ProduktId = 2
                        },
                        new
                        {
                            ProduktBilledeId = 6,
                            Billede = "https://www.komplett.dk/img/p/1200/1149212.jpg",
                            ProduktId = 3
                        },
                        new
                        {
                            ProduktBilledeId = 7,
                            Billede = "https://www.komplett.dk/img/p/1200/1148757.jpg",
                            ProduktId = 4
                        },
                        new
                        {
                            ProduktBilledeId = 8,
                            Billede = "https://www.komplett.dk/img/p/1200/1153467.jpg",
                            ProduktId = 5
                        },
                        new
                        {
                            ProduktBilledeId = 9,
                            Billede = "https://www.komplett.dk/img/p/1200/1156443.jpg",
                            ProduktId = 6
                        },
                        new
                        {
                            ProduktBilledeId = 10,
                            Billede = "https://www.komplett.dk/img/p/1200/1135667.jpg",
                            ProduktId = 7
                        },
                        new
                        {
                            ProduktBilledeId = 11,
                            Billede = "https://www.komplett.dk/img/p/1200/1132405.jpg",
                            ProduktId = 8
                        },
                        new
                        {
                            ProduktBilledeId = 12,
                            Billede = "https://www.komplett.dk/img/p/1200/898464.jpg",
                            ProduktId = 9
                        },
                        new
                        {
                            ProduktBilledeId = 13,
                            Billede = "https://sg-next.imgix.net/medias/sys_master/root/hbd/h3a/13735092912158/MacBook-Pro-16-in-Pure-Front-Space-Gray-SCREEN-result.jpg?w=350&h=350&auto=format&fm=jpg",
                            ProduktId = 10
                        },
                        new
                        {
                            ProduktBilledeId = 14,
                            Billede = "https://www.komplett.dk/img/p/1000/1137677.jpg",
                            ProduktId = 11
                        },
                        new
                        {
                            ProduktBilledeId = 15,
                            Billede = "https://www.komplett.dk/img/p/1200/1150472.jpg",
                            ProduktId = 12
                        },
                        new
                        {
                            ProduktBilledeId = 16,
                            Billede = "https://www.komplett.dk/img/p/1200/1146637.jpg",
                            ProduktId = 13
                        },
                        new
                        {
                            ProduktBilledeId = 17,
                            Billede = "https://www.komplett.dk/img/p/1200/1132707.jpg",
                            ProduktId = 14
                        },
                        new
                        {
                            ProduktBilledeId = 18,
                            Billede = "https://www.komplett.dk/img/p/1200/1153777.jpg",
                            ProduktId = 15
                        },
                        new
                        {
                            ProduktBilledeId = 19,
                            Billede = "https://www.komplett.dk/img/p/1200/1151019.jpg",
                            ProduktId = 16
                        },
                        new
                        {
                            ProduktBilledeId = 20,
                            Billede = "https://www.komplett.dk/img/p/1200/1149587.jpg",
                            ProduktId = 17
                        },
                        new
                        {
                            ProduktBilledeId = 21,
                            Billede = "https://www.komplett.dk/img/p/1200/1138869.jpg",
                            ProduktId = 18
                        },
                        new
                        {
                            ProduktBilledeId = 22,
                            Billede = "https://www.komplett.dk/img/p/1200/1157749.jpg",
                            ProduktId = 19
                        },
                        new
                        {
                            ProduktBilledeId = 23,
                            Billede = "https://www.komplett.dk/img/p/1080/1124639.jpg",
                            ProduktId = 20
                        },
                        new
                        {
                            ProduktBilledeId = 24,
                            Billede = "https://www.komplett.dk/img/p/1080/1124646.jpg",
                            ProduktId = 21
                        },
                        new
                        {
                            ProduktBilledeId = 25,
                            Billede = "https://www.komplett.dk/img/p/1200/1130516.jpg",
                            ProduktId = 22
                        },
                        new
                        {
                            ProduktBilledeId = 26,
                            Billede = "https://www.elgiganten.dk/image/dv_web_D180001002410624/153758/lg-48-cx-4k-oled-tv-oled48cx.jpg?$fullsize$",
                            ProduktId = 23
                        },
                        new
                        {
                            ProduktBilledeId = 27,
                            Billede = "https://www.elgiganten.dk/image/dv_web_D18000100296972/12851/razer-blackwidow-elite-gaming-tastatur.jpg?$fullsize$",
                            ProduktId = 24
                        },
                        new
                        {
                            ProduktBilledeId = 28,
                            Billede = "https://www.komplett.dk/img/p/1200/1144808.jpg",
                            ProduktId = 25
                        },
                        new
                        {
                            ProduktBilledeId = 29,
                            Billede = "https://www.komplett.dk/img/p/1200/1127733.jpg",
                            ProduktId = 26
                        },
                        new
                        {
                            ProduktBilledeId = 30,
                            Billede = "https://www.komplett.dk/img/p/1200/1146944.jpg",
                            ProduktId = 27
                        },
                        new
                        {
                            ProduktBilledeId = 31,
                            Billede = "https://www.komplett.dk/img/p/1200/1150475.jpg",
                            ProduktId = 28
                        },
                        new
                        {
                            ProduktBilledeId = 32,
                            Billede = "https://www.komplett.dk/img/p/1200/1041072.jpg",
                            ProduktId = 29
                        });
                });

            modelBuilder.Entity("Datalayer.Entities.kategori", b =>
                {
                    b.Property<int>("kategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kategoriId");

                    b.ToTable("kategorier");

                    b.HasData(
                        new
                        {
                            kategoriId = 1,
                            Navn = "Grafikkort"
                        },
                        new
                        {
                            kategoriId = 2,
                            Navn = "Bærbar"
                        },
                        new
                        {
                            kategoriId = 3,
                            Navn = "Mobil"
                        },
                        new
                        {
                            kategoriId = 4,
                            Navn = "TV"
                        },
                        new
                        {
                            kategoriId = 5,
                            Navn = "Tastatur"
                        },
                        new
                        {
                            kategoriId = 6,
                            Navn = "Mus"
                        });
                });

            modelBuilder.Entity("Datalayer.Entities.Ordre", b =>
                {
                    b.HasOne("Datalayer.Entities.Kunde", "Kunde")
                        .WithMany("Ordrer")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datalayer.Entities.OrdreProdukt", b =>
                {
                    b.HasOne("Datalayer.Entities.Ordre", "Ordre")
                        .WithMany("Produkter")
                        .HasForeignKey("OrdreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalayer.Entities.Produkt", "Produkt")
                        .WithMany("Ordrer")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Datalayer.Entities.Produkt", b =>
                {
                    b.HasOne("Datalayer.Entities.kategori", "Kategori")
                        .WithMany("Produkts")
                        .HasForeignKey("KategoriId");

                    b.HasOne("Datalayer.Entities.Producent", "Producent")
                        .WithMany("Produkter")
                        .HasForeignKey("ProducentId");
                });

            modelBuilder.Entity("Datalayer.Entities.ProduktBillede", b =>
                {
                    b.HasOne("Datalayer.Entities.Produkt", "Produkt")
                        .WithMany("ProduktBilleder")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
